name: Publish to GitHub Package repo

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: ./gradlew build
    - name: Publish
      run: ./gradlew publish
